### PR TITLE
fix(docs): rename README to README.md

### PR DESCRIPTION
**Pull request by d2s**
- Rename `README` to `README.md`
- Fix document rendering issue from GitHub

### CODE REVIEW

**Comment by jabranr** [comment]
Don't think this is required. Especially because Eleventy will pick this up and generate a page in build.

**Comment by d2s** [comment]
Understandable concern with the generated files.

But maybe you could follow the official recommendation from Eleventy itself,
as they recommend having `.eleventyignore` file on the default site template repository.
A lot of other starter kits do it similarly.

Example:
https://github.com/11ty/eleventy-base-blog/blob/master/.eleventyignore

It is similar to `.gitignore` file, allowing to filter out unrelated files.

**Comment by jabranr** [comment]
@d2s That sounds good to me. Thank you for bringing it to my intention. Going to re-open the PR so you can make further modifications.

**Comment by jabranr** [comment]
Closing this as no activity. Re-open if there are more updates.

**Pull request closed without merging**
